Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,28 +13,42 @@ jobs:
     - name: Check out repository
       uses: actions/checkout@v3
 
+    # Configuración de Node.js con una versión más reciente, por ejemplo 18
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
-        node-version: 16
+        node-version: '18'  # Mejor usar una versión más reciente de Node.js
 
+    # Limpiar el cache de node_modules y reinstalar dependencias
     - name: Install dependencies
-      run: powershell -ExecutionPolicy Bypass -Command "npm install"
+      run: |
+        npm ci  # npm ci es más rápido y fiable para CI/CD ya que limpia node_modules
 
+    # Crear build del proyecto React
     - name: Build React app
       run: npm run build
 
+    # Listar archivos generados para debug (verificar dist)
     - name: List files for debugging
-      run: ls -la && ls -la dist || echo "Dist directory not found"
+      run: |
+        ls -la
+        ls -la dist || echo "Dist directory not found"
 
+    # Asegurarte de que el directorio de destino existe antes de copiar
+    - name: Ensure deployment directory exists
+      run: |
+        if (-not (Test-Path "C:\inetpub\DeployActions\")) {
+          New-Item -Path "C:\inetpub\DeployActions\" -ItemType Directory
+        }
+
+    # Copiar los archivos generados al servidor IIS
     - name: Copy files to IIS server
       run: |
-        # Si el runner ya está en el servidor IIS, puedes usar comandos locales en lugar de SCP
-        # Suponiendo que tienes IIS configurado para recibir los archivos
         xcopy /E /I /Y dist\* C:\inetpub\DeployActions\
 
+    # Notificar por Teams al finalizar el despliegue
     - name: Notify Teams
       run: |
         curl -H 'Content-Type: application/json' \
-          -d '{"text":"El despliegue de ${{ vars.NOMBRE_PROYECTO }} ha sido completado exitosamente en el servidor IIS desde GitHub"}' \
-          https://iberomx.webhook.office.com/webhookb2/b69cf58a-145e-4bc3-a475-640753321d68@40152134-6f8a-46f7-bc22-240f7c7c2455/IncomingWebhook/8ab337806a4f48a6bac8364964376f87/cfafb0dc-c85f-48b5-b351-7987e37a8b4c/V25b0WXu1B_fsmLHVdlXEEtWZp1mybiHnxBRsA8DOw8S81
+          -d '{"text":"El despliegue de '${{ vars.NOMBRE_PROYECTO }}' ha sido completado exitosamente en el servidor IIS desde GitHub"}' \
+          ${{ secrets.TEAMS_WEBHOOK_URL }}
